packages/viewer/cypress/e2e/space.spec.ts, packages/viewer/public/refs/heads/main.json, packages/viewer/src/components/Properties/Spaces.svelte, packages/viewer/src/components/Spaces/Properties.svelte, packages/viewer/src/components/Traits/Related.svelte
by indexing the correct related trait type
fixes: #68
=> fix: filtering properties related to a space

packages/viewer/cypress/e2e/typesetting.spec.ts, packages/viewer/src/context.ts, packages/viewer/src/parser/internalLinks.test.ts, packages/viewer/src/parser/internalLinks.ts, packages/viewer/src/parser/renderer.ts, packages/viewer/vite.config.js
to include a description of the trait value
Fixes #79
=> format {S#|P#} display

packages/viewer/src/components/Properties/List.svelte, packages/viewer/src/components/Search/Search.svelte, packages/viewer/src/components/Shared/Filter.svelte, packages/viewer/src/components/Shared/Formula/Input/Formula.svelte, packages/viewer/src/components/Spaces/List.svelte, packages/viewer/src/components/Theorems/List.svelte, packages/viewer/src/routes/(app)/properties/+page.ts, packages/viewer/src/routes/(app)/spaces/all/+page.ts, packages/viewer/src/routes/(app)/theorems/+page.ts, packages/viewer/src/stores/list.ts, packages/viewer/src/stores/urlSearchParam.ts
fixes #77
For each of spaces, properties, theorems, explore page
=> fix filter reactivity

packages/viewer/cypress/e2e/typesetting.spec.ts, packages/viewer/src/components/Shared/Typeset.svelte, packages/viewer/vite.config.js
=> typeset internal links

packages/viewer/src/components/Traits/Related.svelte
=> use action verbs in robot toggle

packages/viewer/src/components/Properties/List.svelte, packages/viewer/src/components/Spaces/List.svelte, packages/viewer/src/components/Theorems/List.svelte
to keep the list view more information-dense
from https://github.com/orgs/pi-base/discussions/464
=> tweak list table widths

packages/viewer/src/components/Properties/Show.svelte, packages/viewer/src/routes/(app)/properties/[id]/+page.svelte
See discussion at https://github.com/orgs/pi-base/discussions/495
=> reorder tabs on properties show

packages/viewer/cypress/e2e/search.spec.ts, packages/viewer/src/components/Shared/Formula.svelte, packages/viewer/src/components/Shared/Formula/Atom.svelte, packages/viewer/src/components/Shared/Formula/Compound.svelte
=> remove spacing around brackets

packages/viewer/src/components/Theorems/Converse.svelte
Adds call to action when a theorem has no counterexamples or a proof for its converse.
=> theorem converses

packages/compile/package.json, packages/compile/src/watch/server.ts, packages/viewer/src/components/Dev/Explore.svelte, packages/viewer/src/constants.ts, packages/viewer/src/routes/+layout.svelte, packages/viewer/src/routes/+layout.ts, packages/viewer/src/stores/index.ts, packages/viewer/src/util.ts, packages/viewer/vite.config.js, pnpm-lock.yaml
Set `VITE_BUNDLE_SSE` to cause the frontend to subscribe to server sent events from the `VITE_BUNDLE_HOST` at /sse.
=> feat: optionally trigger frontend reload on bundle rebuild

.dockerignore, .github/workflows/data-dev.yaml, images/data-dev/Dockerfile, images/data-dev/entrypoint.sh, package.json, packages/core/vite.config.ts, packages/viewer/vite.config.js, pnpm-lock.yaml
Builds and publishes a container suitable for `pi-base/data` development, including a dev-mode `viewer` and `compiler`.
=> feat: build and publish data-dev container

.github/workflows/e2e.yaml, .prettierignore, packages/core/test/e2e.test.ts, packages/core/test/fixtures/bundle.min.json, packages/viewer/cypress.config.ts, packages/viewer/cypress/e2e/deduction.spec.ts, packages/viewer/cypress/e2e/loading.spec.ts, packages/viewer/cypress/e2e/search.spec.ts, packages/viewer/cypress/e2e/space.spec.ts, packages/viewer/cypress/fixtures/main.min.json, packages/viewer/cypress/support/constants.ts, packages/viewer/cypress/support/index.ts, packages/viewer/package.json, pnpm-lock.yaml
- works against cloudflare
- removes `isLegacy` compatability shim
=> ci: update cypress suites

packages/viewer/package.json, packages/viewer/src/components/Home.svelte, pnpm-lock.yaml
=> Fix trailing slashes in routes

packages/viewer/src/routes/(app)/theorems/[id]/converse/+page.svelte, packages/viewer/src/routes/(app)/theorems/[id]/references/+page.svelte
=> fix titles

packages/viewer/src/components/Shared/Reference.svelte
=> typeset reference

packages/viewer/src/components/Shared/Cite.svelte
=> Fixed citation button

packages/viewer/src/components/Properties/Cell.svelte, packages/viewer/src/components/Properties/List.svelte, packages/viewer/src/components/Spaces/Cell.svelte, packages/viewer/src/components/Spaces/List.svelte, packages/viewer/src/components/Traits/Table.svelte, packages/viewer/src/constants.ts, packages/viewer/src/stores/list.test.ts, packages/viewer/src/stores/list.ts, packages/viewer/src/stores/search.ts
=> Search in other tables

packages/viewer/src/components/Shared/ExtMarkdown.svelte
Adding names to pi-base citations
=> External markdown enhancements

packages/core/src/Formula.ts
I don't know how to add an appropriate test for this PR. But it works in my environment.
=> fix: ?property formula, resolve #205

packages/core/src/Logic/Prover.ts
Continuation of #206.
See https://github.com/pi-base/web/pull/206#issuecomment-2530148331 for details.
=> fix: ?property formula (part 2), complete deduction

packages/viewer/package.json, packages/viewer/src/environment.ts, packages/viewer/src/errors.ts, packages/viewer/src/honeycomb.ts, packages/viewer/src/routes/+layout.ts, pnpm-lock.yaml
=> try out honeycomb frontend monitoring

packages/viewer/src/components/Dev/Preview.svelte
=> Update Preview.svelte to use short internal links
